# Generated by Django 5.2.2 on 2025-06-15 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TreanferMerket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='TreanferMerket.position', verbose_name='Позиция'),
        ),
    ]
