# Generated by Django 5.2.2 on 2025-06-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TreanferMerket', '0002_alter_player_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_club_logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='player_club_logos/', verbose_name='Загруженное фото логотипа клуба'),
        ),
        migrations.AddField(
            model_name='player',
            name='player_flag_image',
            field=models.ImageField(blank=True, null=True, upload_to='player_flags/', verbose_name='Загруженное фото флага'),
        ),
        migrations.AlterField(
            model_name='player',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='players/', verbose_name='Загруженное фото игрока'),
        ),
        migrations.AlterField(
            model_name='player',
            name='image_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Фото игрока (URL)'),
        ),
    ]
