# Generated by Django 5.2.2 on 2025-06-15 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TreanferMerket', '0003_player_player_club_logo_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='TreanferMerket.club', verbose_name='Клуб'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='TreanferMerket.nation', verbose_name='Страна'),
        ),
    ]
