# Generated by Django 5.2.2 on 2025-06-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TreanferMerket', '0004_alter_player_club_alter_player_nation'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='purchase_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество покупок'),
        ),
    ]
