# Generated by Django 5.2.2 on 2025-06-15 17:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TreanferMerket', '0005_player_purchase_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferlisting',
            name='last_price_update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время последнего обновления цены'),
            preserve_default=False,
        ),
    ]
